version: '3.1'
services:
  dbpostgresql:
    image: postgres:latest
    networks:
      - spring-boot-network
    container_name: dbpostgresql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=harry_potter
  redis:
    image: redis:latest
    networks:
      - spring-boot-network
    container_name: redis-cache
    expose:
      - "6379"
    ports:
      - "6379:6379"

networks:
  spring-boot-network:
    driver: bridge